// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WatchArchive.Server.Data;

#nullable disable

namespace WatchArchive.Server.Migrations
{
    [DbContext(typeof(WatchArchiveDbContext))]
    [Migration("20260925233440_AddBasicAttributes")]
    partial class AddBasicAttributes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WatchArchive.Server.Models.Attributes.AttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("attribute_definitions");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Attributes.BooleanAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_definition_id");

                    b.Property<Guid>("RatedEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("rated_entry_id");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("RatedEntryId");

                    b.ToTable("boolean_attributes");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Attributes.DateAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_definition_id");

                    b.Property<Guid>("RatedEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("rated_entry_id");

                    b.Property<DateTime>("Value")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("RatedEntryId");

                    b.ToTable("date_attributes");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Attributes.LongTextAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_definition_id");

                    b.Property<Guid>("RatedEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("rated_entry_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("RatedEntryId");

                    b.ToTable("long_text_attributes");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Attributes.NumberAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_definition_id");

                    b.Property<Guid>("RatedEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("rated_entry_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("RatedEntryId");

                    b.ToTable("number_attributes");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Attributes.ShortTextAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_definition_id");

                    b.Property<Guid>("RatedEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("rated_entry_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("RatedEntryId");

                    b.ToTable("short_text_attributes");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Attributes.StarRatingAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_definition_id");

                    b.Property<Guid>("RatedEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("rated_entry_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("RatedEntryId");

                    b.ToTable("star_rating_attributes");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Attributes.UrlAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_definition_id");

                    b.Property<Guid>("RatedEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("rated_entry_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("RatedEntryId");

                    b.ToTable("url_attributes");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.RatedEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<decimal>("OverallRating")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("overall_rating");

                    b.Property<Guid>("ThumbnailId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ThumbnailId");

                    b.HasIndex("UserId");

                    b.ToTable("rated_entries");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Thumbnail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AutoGenerateKeyword")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("auto_generate_keyword");

                    b.Property<string>("ImgLoc")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("img_loc");

                    b.Property<bool>("UseAutoGenerate")
                        .HasColumnType("boolean")
                        .HasColumnName("use_auto_generate");

                    b.HasKey("Id");

                    b.ToTable("thumbnails");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Attributes.AttributeDefinition", b =>
                {
                    b.HasOne("WatchArchive.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Attributes.BooleanAttribute", b =>
                {
                    b.HasOne("WatchArchive.Server.Models.Attributes.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchArchive.Server.Models.RatedEntry", "RatedEntry")
                        .WithMany()
                        .HasForeignKey("RatedEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("RatedEntry");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Attributes.DateAttribute", b =>
                {
                    b.HasOne("WatchArchive.Server.Models.Attributes.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchArchive.Server.Models.RatedEntry", "RatedEntry")
                        .WithMany()
                        .HasForeignKey("RatedEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("RatedEntry");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Attributes.LongTextAttribute", b =>
                {
                    b.HasOne("WatchArchive.Server.Models.Attributes.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchArchive.Server.Models.RatedEntry", "RatedEntry")
                        .WithMany()
                        .HasForeignKey("RatedEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("RatedEntry");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Attributes.NumberAttribute", b =>
                {
                    b.HasOne("WatchArchive.Server.Models.Attributes.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchArchive.Server.Models.RatedEntry", "RatedEntry")
                        .WithMany()
                        .HasForeignKey("RatedEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("RatedEntry");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Attributes.ShortTextAttribute", b =>
                {
                    b.HasOne("WatchArchive.Server.Models.Attributes.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchArchive.Server.Models.RatedEntry", "RatedEntry")
                        .WithMany()
                        .HasForeignKey("RatedEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("RatedEntry");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Attributes.StarRatingAttribute", b =>
                {
                    b.HasOne("WatchArchive.Server.Models.Attributes.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchArchive.Server.Models.RatedEntry", "RatedEntry")
                        .WithMany()
                        .HasForeignKey("RatedEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("RatedEntry");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Attributes.UrlAttribute", b =>
                {
                    b.HasOne("WatchArchive.Server.Models.Attributes.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchArchive.Server.Models.RatedEntry", "RatedEntry")
                        .WithMany()
                        .HasForeignKey("RatedEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("RatedEntry");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.Category", b =>
                {
                    b.HasOne("WatchArchive.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WatchArchive.Server.Models.RatedEntry", b =>
                {
                    b.HasOne("WatchArchive.Server.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("WatchArchive.Server.Models.Thumbnail", "Thumbnail")
                        .WithMany()
                        .HasForeignKey("ThumbnailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchArchive.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Thumbnail");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
