namespace WatchArchive.Server.DTOs.ResponseDTOs;

public class ThumbnailResponse
{
    public Guid Id { get; set; }

    public string? ImgLoc { get; set; }

    public bool UseAutoGenerate { get; set; }

    public string? AutoGenerateKeyword { get; set; }

    public string? AutoGeneratedImgLoc { get; set; }
}
